export const REGISTRATION_BEGIN = 'REGISTRATION_BEGINS';
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
export const REGISTRATION_UNSUCCESSFUL = 'REGISTRATION_UNSUCCESSFUL';
export const REGISTRATION_REJECTED = 'REGISTRATION_REJECTED';
